baseURL = 'https://laboratorij-km.github.io/matjaz.kukar/' # change member_repository to your repository name
languageCode = 'en-us'
title = 'Matja≈æ Kukar'
theme = "member-theme"
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/" 
    weight = 1

  [[menu.main]]
    name = "Lecturing"
    url = "/lecturing/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3


